name: my_first_job

on: 
- push
- workflow_dispatch

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
    first_job:
        strategy:
          matrix:
            os: [ubuntu-latest,windows-latest]
            say: ["Hi my name is char lizard","I am dragon"]
        timeout-minutes: 3
        name: First Job
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout
          uses: actions/checkout@v6.0.2
        - name: List cat README
          run: |
           echo "My first GITHUB ACTION"
           ls  
           cat README.md
        - name: install cowsay
          run: sudo apt install cowsay -y
        - name: generate ascii artwork
          run: cowsay -f dragon "${{ matrix.say }}" > dragon.txt
        - name: upload artifact
          uses: actions/upload-artifact@v7.0.1
          with: 
            name: dragon.txt
            path: ./dragon.txt

        - name: sleep
          run: sleep 600
    test:
        name: test Job
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: download artifact
          uses: actions/download-artifact@v8
          with:
            name: dragon.txt

        - name: print ascii art
          run: cat dragon.txt