name: my_first_job

on: push

jobs:
    first_job:
        name: First Job
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "My first GITHUB ACTION"
        - name: Checkout
          uses: actions/checkout@v6.0.2
        - name: List Files
          run: ls  
        - name: cat Readme
          run: cat README.md
